#!/usr/bin/python3

import requests
import urllib
import re
import os

def get_valid_filename(s):
    s = str(s).strip().replace(' ', '_')
    return re.sub(r'(?u)[^-\w.]', '', s)

def export_posts(posts: list[str]):
    for post in posts:
        text = requests.get(post).text

        imgs = re.findall('data-src="(/thumbnail/data.*\\.(jpg|png|gif))"', text)
        imgs = ["https://kemono.party" + img[0] for img in imgs]

        title = re.findall('<title>\n    &#34;(.*)&#34;', text)[0]
        title = title if len(title) != 0 else get_valid_filename(post)

        vids = re.findall('href="(/data/.*\\.(mp4|mkv|mov|avi|wmv))"', text)
        vids = ["https://kemono.party" + vid[0] for vid in vids]

        print(f"-------- {title} --------")

        title = get_valid_filename(title)

        try:
            os.mkdir(title)
        except Exception:
            pass

        for idx, img in enumerate(imgs):
            print(img)
            ext = os.path.splitext(f"{img}")[-1]
            urllib.request.urlretrieve(img, f"{title}/{idx}{ext}")

        for idx, vid in enumerate(vids):
            print(vid)
            ext = os.path.splitext(f"{vid}")[-1]
            urllib.request.urlretrieve(vid, f"{title}/{idx}{ext}")

def export_user_by_id(id: int):
    os.mkdir(str(id))
    os.chdir(str(id))

    idx = 0
    posts = []
    while True:
        url = f"https://kemono.party/fanbox/user/3316400?o={idx}"
        text = requests.get(url).text

        print(url)

        if re.findall("Nobody here but us chickens!", text):
            break

        posts.extend(["https://kemono.party/fanbox/user/3316400/post/" + text for text in re.findall('/post/(.*)"', text)])

        idx+=50

    export_posts(posts)

export_user_by_id(int(input("enter user id: ")))
