#!/usr/bin/python3

import requests
import urllib
import re
import os
from sys import argv

def get_valid_filename(s):
    s = str(s).strip().replace(' ', '_')
    return re.sub(r'(?u)[^-\w.]', '', s)

def export_posts(posts: list[str]):
    for post in posts:
        text = requests.get(post).text

        imgs = re.findall('data-src="(/thumbnail/data.*\\.(jpg|png|gif))"', text)
        imgs = ["https://kemono.party" + img[0] for img in imgs]

        title = re.findall('<title>\n\s+&#34;(.*)&#34;.*\s*<\/title>', text)[0]

        vids = re.findall('href="(/data/.*\\.(mp4|mkv|mov|avi|wmv))"', text)
        vids = ["https://kemono.party" + vid[0] for vid in vids]

        print(f"-------- {title} --------")

        title = get_valid_filename(title)

        if len(imgs + vids) == 0:
            continue

        if not os.path.isdir(title):
            os.mkdir(title)

        for idx, url in enumerate(imgs + vids):
            print(url)
            ext = os.path.splitext(f"{url}")[-1]
            urllib.request.urlretrieve(url, f"{title}/{idx}{ext}")

def export_user_by_id(id: int):
    if not os.path.isdir(str(id)):
        os.mkdir(str(id))

    os.chdir(str(id))

    idx = 0
    posts = []
    while True:
        url = f"https://kemono.party/fanbox/user/{id}?o={idx}"
        text = requests.get(url).text

        print(url)

        if re.findall("Nobody here but us chickens!", text):
            break

        posts.extend([f"https://kemono.party/fanbox/user/{id}/post/" + text for text in re.findall('/post/(.*)"', text)])

        idx+=50

    export_posts(posts)

export_user_by_id(int(argv[1]))
