#!/bin/sh

if [ -z "$1" ]; then
    echo "must enter the id of a creator"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "creator specified doesn't exist"
    exit 1
fi

find $1 | grep -E ".*(mp4|mkv|mov|avi|wmv)" | xargs mpv
